### ISSUE TITLE
Webロゴ掲載(Chatwork株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#104]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1xKechSY3JQfcr62J-saqSOVpUcTg075V
リンク先:https://go.chatwork.com/ja/

**Comment by tomoco95** [comment]
#105 で対応中

**Comment by Iwaji** [comment]
11/29URL変更のご連絡あり

＊＊＊＊＊＊＊＊＊＊＊＊

ご担当者様

お世話になります。
Chatwork株式会社の藤井です。

先程、

- ScalaMatsuri Webサイトに掲載するロゴ画像
- ScalaMatsuri Webサイトに掲載する情報(貴社サービスのご説明や求人情報など)の原稿

をGoogleフォームにてお送りさせていただきました。

その際、以下のURLを入力させていただいておりましたが、
変更をお願いできますでしょうか。

変更前: https://go.chatwork.com/ja/
変更後: https://corp.chatwork.com/ja/

お手数をおかけし申し訳ございません。

よろしくお願いいたします。

**Comment by tomoco95** [comment]
done
