### ISSUE TITLE
Webロゴ掲載(WAmazing株式会社様)

### ISSUE THREAD

**Issue by Iwaji** [scalajp/2019.scalamatsuri.org#107]
- [x] リポジトリにロゴを入れる

- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=0B130_pc41DhqMFJQUVVPYVBjQ2c
リンク先:https://info.wamazing.jp/

**Comment by tomoco95** [comment]
#112 で対応中

**Comment by tomoco95** [comment]
done
