### ISSUE TITLE
Webロゴ掲載(SUGAR株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#117]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1oiURnuCkOAu790nV8in-CjE-za0CUGBD
リンク先:https://sugarcorp.jp/

**Comment by tomoco95** [comment]
#119 にて対応済みです。
