### ISSUE TITLE
Web情報掲載(SUGAR株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#131]
---
title: "SUGAR株式会社"
logo: ""
plan: 
link: "https://sugarcorp.jp/"
linkTitle: "ホームページはこちら"
---
#  SUGAR株式会社

SUGARでは、「１：１：N」のライブ動画配信プラットフォーム「SUGAR」を開発しています。

## SUGARの特徴

・アーティスト様から「生」でテレビ電話がかかってきます。 
・テレビ電話がかかってきた方の中からランダムで選ばれた方が通話ができます。 
・お持ちのスマートフォンだけで配信に参加出来ます。 
・「盛り」ができるリアルタイムメイクアップ機能や、顔スタンプ機能があります。

2017年6月設立の産まれたてのスタートアップですが、日本を代表するベンチャーキャピタルや有名な個人投資家の方々から数億円の資金調達を実行しております。

## 開発文化について
高速で高品質な開発を実現し続けるための努力を妥協無く行います。

1.優れた道具を使う - PHPやJava等ではなくScalaやKotlinを / 良いPC。 
2.優れた手法を正しく使う - ドメイン駆動設計、Scrum等 / 聞きかじらない 
3.衛生を維持しよう - レビュー / 不安をテストに 
4.楽をしよう - 手運用をさける / 自動化・スクリプト化

より詳しくは

・2017/10のブログエントリ - 初転職4年間のまとめ、あるいはCTOを辞めたお話 
http://sugitani.hatenablog.com/entry/2017/10/01/122714 
・2015/5のブログエントリ - 技術的負債について考えた 
http://sugitani.hatenablog.com/entry/2015/05/23/205714 
をご参照ください。

## 開発環境
・Macbook Pro 15インチ 2.9GHz / メモリ32GB / SSD 512GB 
・デュアルディスプレイ 
・GitHub / Slack / ... 
・Scala / Swift / Kotlin / TypeScript / ... 
・GCP / AWS / Docker / Kubernetes / Ansible / Akamai / Fastly / ...

## 求人
SUGAR株式会社ではScalaで開発を行う仲間を大募集しています！
 ぜひご応募ください！
https://open.talentio.com/1/c/sugar/requisitions/detail/8639

**Comment by tomoco95** [comment]
done
