### ISSUE TITLE
CFPの掲載@英語: Andrea Peruffoさんによる「Principled SBT」

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#14]
```
---
name: Andrea PEruffo
title: "Principled SBT"
length: 40
audience: Beginner
language: English
twitter: and_prf
github: andreaTP
icon: https://avatars0.githubusercontent.com/u/5792097?s=400&v=4
organization: Codacy / Software Developer
tags:
  - Tools
suggestions:
  - Anyone struggling with Sbt.
contributes:
  - akka.js, sbtcli, shocon, akka, scala.js
speaker_experience:
  - Splash 2015
Scala Days Berlin 2016
BeeScala Ljubljana 2016
ScalaUA Kiev 2017
ScalaSwarm Porto 2017
Devoxx Casablanca 2017
Scala eXchange London 2017
LXScala Lisbon 2018
CurryOn 2018
Scala Italy 2018
Scala eXchange London 2018 (To be done)
---
Everyone has learned over the years to hate SBT enough, it's now time to stand and talk a little more about it.
Like any other library or tool we use in our daily work SBT deserve a little of principled learning, despite the fact most people try to keep the build working with some furious googling and copy-pasting this rarely turns out to be a proper solution.
There are a few(more or less opinionated) principles where SBT sit on, just learning a few basics will enormously boost our productivity, demystify the dragons in our build.sbt and, even, open us new horizons to leverage on it.
```

日本語情報
タイトル - 
概要 - 

- [x] 英語版の掲載

**Comment by eed3si9n** [comment]
@ andreaTP Hi Andrea! The organizers wants you to pick top 3 for "contributes" and "speaker_experience" field.
Also you're encouraged to post URL (of recorded talks or slides) for the "speaker_experience" apparently. Thanks!

**Comment by andreaTP** [comment]
@eed3si9n Hi! ok, that's fair.
In "contributes" we can now list sbt (if I have your blessing :smile: ), akka.js, scala.js.
For "speaker experience":

Scala eXchange London 2017
Don’t Call Me Frontend Framework! A Quick Ride on Akka.Js
https://skillsmatter.com/skillscasts/10951-don-t-call-me-frontend-framework-a-quick-ride-on-akka-js
https://github.com/andreaTP/scalaX2017

CurryOn 2018
Akka.JS and why the actor model matters even in JS's world
https://youtu.be/_Py5LCO3mIw
https://github.com/andreaTP/curryon2018

Scala Italy 2018
Principled SBT
https://gitlab.com/andreaTP/sbt-ws
https://gitlab.com/andreaTP/sbt-ws-slides

**Comment by eed3si9n** [comment]
> In "contributes" we can now list sbt

Yea, totally.

**Comment by eed3si9n** [comment]
By the way, can we change the spelling of sbt? It's all lowercase.

**Comment by andreaTP** [comment]
Sure!

**Comment by grimrose** [comment]
published.
