### ISSUE TITLE
Webロゴ掲載(株式会社ZOZOテクノロジーズ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#142]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1E7B4iAQVC65nWwRmhamemNLAWZ3k4uXU
リンク先:https://tech.zozo.com/

**Comment by Iwaji** [comment]
12/18済
