### ISSUE TITLE
CFPの掲載@和訳: Guillem Iscla さんによる「Scala Future is great. How can I do better?」

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#209]
```
---
name: Guillem Iscla
title: "Scala Futureはすごい。どうしたらさらによくなるか?"
length: 40
audience: Intermediate
language: English
twitter: 
github: https://github.com/GuillemIscla
icon: https://avatars2.githubusercontent.com/u/5903579?s=400&u=d0b10e605d963ad16172e530e87f7dae3e1c9ecc&v=4
organization: SUGAR Inc
tags:
  - Tools, Best Practices, Intro to Scala
suggestions:
  - Anyone who uses concurrency in Scala and has interests on how it works or some tools for managing it
contributes:
  - 
speaker_experience:
  - 
---
Scalaで並列処理を扱うための方法として真っ先に思いつく方法はScala Futuresでしょう。しばらくの間は使用するのには十分でしょう。
Futureの並列処理に問題を感じている人もいらっしゃるでしょう。
すべてのスレッドを使い尽きそうでしたら、スレッドプールをもっと制御したいはずです。また、タスクを順番に実行したり、一部のタスクのみ同期的に処理してほしいと処理したいと悩んでいるかもしれません。あるいは、スレッド内の障害を処理できることは知っているかもしれませんが、それを実行するためのより良い方法があると感じるかもしれません。
今回の講演では、これらの問題を解決する優れたツール (Scala) をいくつか紹介します。
```

英語情報
タイトル - Scala Future is great. How can I do better?
概要 - First approach for everyone in concurrency in Scala is Futures and you can like them enough to stay here for a while.
Now, concurrency can easily put yourself into trouble when you exhaust all your threads and suddenly want more control over your thread pool. On the other hand you might want your tasks to run sequentially or throttle them. Or maybe you know you can handle failures in your threads but also feel there are nicer ways to do it.
In this talk we see some of excellent tools in Scala to manage these and other problems you might have.

- [x] 和訳
- [x] 日本語版の掲載

**Comment by grimrose** [comment]
掲載されたのでcloseします。
