### ISSUE TITLE
CFPの掲載@和訳: Jon Pretty さんによる「Anger Management with Fury」

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#22]
```
---
name: Jon Pretty
title: ""
length: 40
audience: Beginner
language: English
twitter: propensive
github: propensive
icon: https://storage.googleapis.com/revivalist/images/scala.one/jonpretty.jpg
organization: Propensive
tags:
  - Tools
suggestions:
  - The talk should be interesting to anyone who needs to build Scala, but will be particularly interesting to people with complex builds.
contributes:
  - Fury, Magnolia, Contextual, Kaleidoscope
speaker_experience:
  - I present at almost every Scala conference. As one example: https://www.youtube.com/watch?v=26UHdZUsKkE
---

```

英語情報
タイトル - Anger Management with Fury
概要 - Scala's ecosystem has been held back for years by our method of distributing binaries: fragile compatibility, difficult publishing processes, and slow release cycles. Fury aspires to improve how we share Scala software in the future through source dependencies, simplified builds, and a greater liberation to fork, contribute and curate builds.

In this talk, Jon will introduce the concepts behind Fury, and demonstrate how it can be used to manage projects in a fast-evolving Scala ecosystem.

- [x] 和訳
- [x] 日本語版の掲載

**Comment by Keita-N** [comment]
Furyでアンガーマネジメント
Scalaのエコシステムは脆弱な互換性、難しいパブリッシングプロセス、リリースサイクルの遅れなどの、バイナリの配布方法によって何年も押さえつけられてきました。Furyは、ソースの依存関係、単純化されたビルド、およびビルドのフォーク、コントリビュート、作成に対するより大きな解放を通じて、今後、Scalaソフトウェアの共有方法を改善することを目指しています。

このトークでは、Furyの裏側のコンセプトを紹介し、急速に進化するScalaのエコシステムの中でプロジェクトをどのように管理できるのかを示します。

// TODO あとでPR

**Comment by takezoux2** [comment]
タイトルは中２っぽいですが、「Fury: 激怒を持って怒りを制する」とかｗ

**Comment by Keita-N** [comment]
なるほど、Fury = 激怒 なのかw

**Comment by grimrose** [comment]
掲載されたのでcloseします
