### ISSUE TITLE
CFPの掲載@英訳: osiireさんによる「ParsebackでDSL作り」

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#273]
```
---
name: osiire
title: "Build up your DSL using Parseback"
length: 40
audience: Intermediate
language: Japanese
twitter: https://twitter.com/osiire
github: https://github.com/osiire
icon: https://pbs.twimg.com/profile_images/1710330842/me_400x400.png
organization: 
tags:
  - Functional Programming, Software Design and Architecture
suggestions:
  - DSLを作ってみたいけど壁が高いと感じている人
contributes:
  - 
speaker_experience:
  - 
---

```

日本語情報
タイトル - ParsebackでDSL作り
概要 - DSLは複雑な問題を簡潔に記述でき、様々な場面で"ミッシングリング"を埋める強力な手法の一つです。一方で、独自言語を作る事はパースから実行まで考慮すべき事が多く、難易度が高い技術でもあります。しかし、Parsebackと呼ばれるfull CFGをサポートしたライブラリはとても使いやすく、パーシングの主たる課題である曖昧性の解決をうまく支援してくれます。本セッションでは、Parsebackの特徴を紹介しつつ、ScalaにおけるDSL作成の技術的ポイントを解説します。

- [x] 英訳
- [x] 英語版の掲載

**Comment by yohei1126** [comment]
https://github.com/scalajp/2019.scalamatsuri.org/pull/365
