### ISSUE TITLE
Web情報掲載(JSA（テスト）様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#312]
---
title: "JSA（テスト）"
logo: ""
plan: 
link: "https://google.com/"
linkTitle: "Google検索"
---
<<なにかを掲載する>>

**Comment by taisukeoe** [comment]
Zapierがエラーを吐いていたので、テスト投稿。
（Zapierに登録していたgmailアカウントが、なぜかこのGoogleフォームにアクセスできなくなっていた模様…）
