### ISSUE TITLE
Link to Rubén Resino's icon is broken

### ISSUE THREAD

**Issue by yohei1126** [scalajp/2019.scalamatsuri.org#374]
Hi, @rresino 
Your icon is not fond on the link.
https://pbs.twimg.com/profile_images/2629410655/aaeb143bea37b29955f91daba39e9c67_bigger.jpeg
Would yo provide correct one?
Thanks

**Comment by rresino** [comment]
Hi, @yohei1126 
I'm sorry I attach a new img. But if you need a bigger or another please request me.

![avatar_mini](https://user-images.githubusercontent.com/1223861/51863122-818ea880-2340-11e9-9778-eb4c991af849.png)

Thanks and sorry for the inconvenience
