### ISSUE TITLE
CFPの掲載@英訳: 大沼 由弥さんによる「さよなら breakOut」

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#387]
```
---
name: Yuya Onuma
title: ""
length: 10
audience: Intermediate
language: Japanese
twitter: 
github: gion-xy
icon: https://pbs.twimg.com/profile_images/1079282569479241728/vn_sOqmD_400x400.jpg
organization: Fringe81株式会社
tags:
  - Others
suggestions:
  - 新しめの Scala に興味があるひと
contributes:
  - 
speaker_experience:
  - 
---

```

日本語情報
タイトル - さよなら breakOut
概要 - Scala 2.13 ではコレクションライブラリに変更が入り、一部の機能は削除されることになっています。
そのなかで比較的影響が大きいであろうものとして、 CanBuildFrom クラスの削除とそれに伴う breakOut メソッドの削除があげられます。

本発表では、これらが削除されたあとの世界における代替コードの記法や、2.13 での新実装の利点などについて説明できればと思います。

- [x] 英訳
- [x] 英語版の掲載

**Comment by NoriakiHoriuchi** [comment]
すでに英語版が掲載されているようなので閉じますね！
