### ISSUE TITLE
Webロゴ掲載(Fringe81株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#391]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/file/d/1WPArB-zmU_kFBJf08QLIStSEPpmNjUuJ/view?usp=sharing
リンク先:https://www.fringe81.com/join/engineer/

**Comment by YumiShibazaki** [comment]
#696 で対応しました
