### ISSUE TITLE
CFPの掲載@英訳: 下村 朋之, 田邊 義真さんによる「悩める開発者に贈る ~サービスの継続的な成長を支える分析設計手法」

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#427]
```
---
name: Tomoyuki Shimomura, Yoshimasa Tanabe
title: ""
length: 90
audience: Intermediate
language: Japanese
twitter: @s10myk4, @emaggame
github: https://github.com/s10myk4
icon: https://d2mxuefqeaa7sj.cloudfront.net/s_84C0A5896E9B8ADFA74D479EF9473FCB5BC38BDABDA062C6718D295F2C3E3603_1548505719997_scalamatsuri2019-icon.png
organization: 株式会社セプテーニ・オリジナル エンジニア
tags:
  - Best Practices, Software Design and Architecture
suggestions:
  - * チーム開発に取り組んでるいて、開発手法に課題を感じる
* チームとしての品質を担保したい人
* 要件定義、設計が好きな人
contributes:
  - Scala Matsuri 2018 アンカンファレンス, 市ヶ谷 Geek Night, JJUG
speaker_experience:
  - 
---

```

日本語情報
タイトル - 悩める開発者に贈る ~サービスの継続的な成長を支える分析設計手法
概要 - あなたはチーム開発の中で、要件の曖昧さを感じたり、モデリングがしっくりこないといった感じることはないだろうか？
個人のセンスやスキルによってモデリングや設計がなされているような現場をよく耳にする。このような状態が続くと、新機能の追加コストが高くなるなど、負債となりえる様々な悪影響をもたらすことは想像に難くないだろう。

ここでは直感に頼らずに形式的なアプローチで要求の把握からモデリング、詳細設計までを導く方法を紹介する。また、各フェーズのアウトプットを Scala で書いており、この手法において Scala がどのような有用性を持つかについても言及したい。 
それによって我々はビジネスの要求を捉え、チームとして継続的に一貫した品質のソフトウェアを提供したいのである。

#キーワード Scala/チーム開発/ユースケース駆動開発/DDD/クリーンアーキテクチャ/Event Storming

- [ ] 英訳
- [ ] 英語版の掲載

**Comment by taisukeoe** [comment]
contributesとspeaker_experienceを入れ替える
