### ISSUE TITLE
CFPの掲載@和訳: Changlin Li さんによる「Introduction to Lenses (and other Optics)」

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#495]
```
---
name: Changlin Li
title: ""
length: 40
audience: Intermediate
language: English
twitter: 
github: https://github.com/changlinli
icon: https://f001.backblazeb2.com/file/Grabbag/profile_small.jpg
organization: 
tags:
  - Functional Programming, Best Practices
suggestions:
  - Beginning functional programmers who may have vaguely heard of lenses but don't know what they are or how they work
contributes:
  - 
speaker_experience:
  - Northeast Scala 2018 (slides: https://github.com/changlinli/types_presentation_slides, video: https://www.youtube.com/watch?v=Csj3lzsr0_I)
---

```

英語情報
タイトル - Introduction to Lenses (and other Optics)
概要 - While immutable data structures have a lot of benefits, accessing or modifying select parts of them can be annoying and full of boilerplate. The family of abstractions known as optics is one solution to this problem. 

This talk will be a gentle introduction to optics through algebraic datatypes, as it turns out the two share a very close relationship. We'll see how optics let us retrofit ADT interfaces onto any immutable data structure and how this provides a solution.

We'll also talk about when optics are NOT the right answer and how to spot it.

- [ ] 和訳
- [ ] 日本語版の掲載

**Comment by taisukeoe** [comment]
ファイル名はChanglinLi_2とする
