### ISSUE TITLE
Webロゴ掲載(たかはし通知のテスト様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#58]
- [ ] リポジトリにロゴを入れる
- [ ]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1w53zXmlwwoj_Q-chIiebFnerF0j1-TfE
リンク先:http://2019.scalamatsuri.org

**Comment by tomoco95** [comment]
テストなので閉じます
