### ISSUE TITLE
Webロゴ掲載(株式会社サイバーエージェント様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#66]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=12Hlp9qZ6dKxXM43Cr9HXneUsFUgs3vkv
リンク先:https://adtech.cyberagent.io/

**Comment by taisukeoe** [comment]
掲載完了
