### ISSUE TITLE
Webロゴ掲載(アルプ株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#76]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1mvidagpTeXPPJYe4JM5D6Isjf5vf-tHz
リンク先:https://thealp.co.jp/

**Comment by tomoco95** [comment]
done
