### ISSUE TITLE
Webロゴ掲載(株式会社ファンコミュニケーションズ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#77]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1bgOh4gbbrPnc0kh9CgWRfktSZMxhVtn0
リンク先:https://www.fancs.com/

**Comment by tomoco95** [comment]
done
