### ISSUE TITLE
Fringeさんのロゴを修正する

### ISSUE THREAD

**Issue by Iwaji** [scalajp/2019.scalamatsuri.org#777]
Fringeさんから余白を調整して、再掲載してほしいと連絡有。

- [x]  ロゴを修正する（@YumiShibazaki）

- [x] 修正が完了したら、完了した旨Fringeさんに連絡する（@iwaji）

**Comment by YumiShibazaki** [comment]
@Iwaji 
ロゴの修正完了しました！

**Comment by YumiShibazaki** [comment]
#776 で対応しました。

**Comment by Iwaji** [comment]
2/14済
