### ISSUE TITLE
Webロゴ掲載(株式会社アットウェア様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#796]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1t-JWJ0fFPCcwgD9FN-tWpTUTne8-yQnz
リンク先:https://www.atware.co.jp/

**Comment by tomoco95** [comment]
@YumiShibazaki ロゴのサイズ調整しておきました！
https://drive.google.com/file/d/1i_knAHRv4RT2BuFTSDVDNvvzNmK1TgyP/view?usp=sharing

**Comment by YumiShibazaki** [comment]
#799 で対応しました。
