### ISSUE TITLE
Webロゴ掲載(TIS株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#797]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/file/d/1mPLqUGhUgGeXaAsBRuB9OcMOZKuIvxOS/view?usp=sharing
リンク先:https://www.tis.co.jp/career/

**Comment by tomoco95** [comment]
ロゴのサイズ変更しました！こちらを使ってもらえればと思います。
https://drive.google.com/file/d/1M8CmtTxPrwYCU9V4_7ITFzVx_jEf_ayG/view?usp=sharing

**Comment by YumiShibazaki** [comment]
#799で対応しました。
