### ISSUE TITLE
Web情報掲載(株式会社虎の穴様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#798]
---
title: "株式会社虎の穴"
logo: ""
plan: 
link: "https://yumenosora.co.jp/tora-lab"
linkTitle: "採用サイトはこちら"
---
株式会社虎の穴

株式会社虎の穴は同人誌を主に委託販売を行う同人ショップです。
全国の主要都市に店舗をおき、通販サイトも運営しております。
通販サイトは会社の売上の約半分を担う重要なビジネス基盤となっております。年々増加しているお客様の需要を実現するために、2018年6月には大規模リニューアルを行いました。
主な開発言語はJavaで社内エンジニアでの内製化を実現しました。今後はJava言語だけでなく、ScalaなどのJavaVM言語にも注目して社内エンジニアの技術向上を目指しています。

【虎の穴ラボ】
株式会社虎の穴ではWeb開発を行う専門部署「虎の穴ラボ」があります。
虎の穴ラボメンバーは、通販サイト開発チームと、新規サービス開発チームに分けられます。
新規サービスには、主にクリエイター支援サイト「Fantia」や自作のイラストをグッズにできる「とらのあなクラフト」などがあります。
両チームとも、クリエイターのファミリーになることをビジョンにお客様の日々の要望に答えながら開発・運用を行っております。

【採用について】
虎の穴ラボでは、Web開発技術を活かして業界を盛り上げてくれる熱意あるエンジニアを募集しています。
是非、お気軽に採用サイトからお問い合わせください！

**Comment by YumiShibazaki** [comment]
#800で対応しました。
