### ISSUE TITLE
大名スポンサーのロゴの並びが崩れる

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2019.scalamatsuri.org#801]
おそらく #715 と同じく、svgファイルの縦横サイズの問題だろうか？
<img width="973" alt="2019-03-05 7 55 50" src="https://user-images.githubusercontent.com/1506707/53768483-4c1b4300-3f1c-11e9-88c9-ceb7daece8eb.png">

**Comment by taisukeoe** [comment]
@tomoco95 時間あるときに、こちらの確認をお願いできますか？

**Comment by grimrose** [comment]
これの原因は /img/logo/quocard.png の縦横比が微妙にズレてるからですね

**Comment by tomoco95** [comment]
#802 でロゴサイズ修正のPullRequest出しました！

**Comment by tomoco95** [comment]
クオカードのロゴが右上に来た時に表示が崩れなければ、直ってると判断して問題ないでしょうか。私から見える画面では大丈夫そうです。
[![Screenshot from Gyazo](https://gyazo.com/5c6cc19274c1a9719b786ca5c8e16992/raw)](https://gyazo.com/5c6cc19274c1a9719b786ca5c8e16992)
@taisukeoe 念のため、麻植さんのブラウザでも確認お願いできますか？

**Comment by taisukeoe** [comment]
確認しました！ 👍
