### ISSUE TITLE
Update en/ma2k8_1.md 

### ISSUE THREAD

**Issue by grimrose** [scalajp/2019.scalamatsuri.org#813]
`ma2k8_1.md` の変更に伴う翻訳の修正
ref #812

**Comment by grimrose** [comment]
https://github.com/scalajp/2019.scalamatsuri.org/pull/812/files

> 日: 私が試したそれぞれのメリットデメリットと、1番良い形を実現できる(と思っている)Effの紹介をします。

> 英: In this talk, I will cover the pros and cons of each of the option that I've tried, and explore the merits of using Eff type to achieve the most.

ニュアンスとか変わっていなければ、closeしたいと思いますが、いかがでしょう?

@eed3si9n @taisukeoe

**Comment by taisukeoe** [comment]
変わってないと思うので、そのままでokです！
