### ISSUE TITLE
Webロゴ掲載(株式会社技術評論社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#814]
- [ ] リポジトリにロゴを入れる
- [ ]  ymlファイルを変更する

ロゴ画像: https://drive.google.com/open?id=1ldiRhNEIz093SacNU4-qKWvHpN2J7RZ5
リンク先:http://gihyo.jp/

**Comment by YumiShibazaki** [comment]
#815 で対応しました。
