### ISSUE TITLE
Webロゴ掲載(マーベリック株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#82]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1CZ9kkckUkUlNCoPUFDgyVsN-eE9YXGFY
リンク先:https://www.mvrck.co.jp

**Comment by tomoco95** [comment]
#83 で対応中

**Comment by tomoco95** [comment]
done
