### ISSUE TITLE
「アンカンファレンスとは?」のリンクが404

### ISSUE THREAD

**Issue by akiomik** [scalajp/2019.scalamatsuri.org#820]
トップページのアンカンファレンス DAYのタイムテーブル上部にある「アンカンファレンスとは?」「What is unconference?」のリンクがja/enともに切れています。

- https://2019.scalamatsuri.org/#day2table

ja/enともに https://2019.scalamatsuri.org/ja/unconference/ を参照していますが該当するファイルはなさそうです。

https://github.com/scalajp/2019.scalamatsuri.org/blob/master/_data/program_en.yml#L280
https://github.com/scalajp/2019.scalamatsuri.org/blob/master/_data/program_ja.yml#L278

**Comment by grimrose** [comment]
ありがとうございます。

2018からのコピー漏れですね。

対応します。
