### ISSUE TITLE
Webロゴ掲載(株式会社マイクロアド様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#824]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1DVFpcSxCqFg_4KERgAbjBQFbufCuR1GB
リンク先:https://www.microad.co.jp

**Comment by tomoco95** [comment]
ロゴのサイズを20:7に変更しました。
https://drive.google.com/file/d/1uf-QAJH2CzPP-9ude3Hx_r9biqvj4ych/view?usp=sharing

**Comment by YumiShibazaki** [comment]
#825 で対応しました。
