### ISSUE TITLE
Webロゴ掲載(株式会社FOLIO様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#827]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1EpxRnX0JJwLZ_PgwvlCNsaKc_wEGU71h
リンク先:https://corp.folio-sec.com/

**Comment by tomoco95** [comment]
@YumiShibazaki ロゴのサイズ調整しました。
https://drive.google.com/file/d/1aELoBHEk7tCdE5FcoBLIAsiIgiIGaXgn/view?usp=sharing

**Comment by YumiShibazaki** [comment]
#833 で対応しました。
