### ISSUE TITLE
Web情報掲載(WAmazing株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#834]
---
title: "WAmazing株式会社"
logo: ""
plan: 
link: "https://www.wantedly.com/companies/wamazing/post_articles/144442"
linkTitle: "Scala社員エンジニアへのインタビュー記事はこちら"
---
WAmazingは「日本を楽しみ尽くす、Amazingな人生に。」をビジョンに、日本の観光をより多くの人たちに知ってもらうべく、現在は外国人観光客に向けてサービスを提供中です。
その裏側では、Scalaを用いているサービスも複数あり、Scalaを活用したいエンジニアを絶賛募集しております。

**Comment by YumiShibazaki** [comment]
#838 で対応しました。
