### ISSUE TITLE
タイムテーブルの言語と難易度の表記をわかりやすくする

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2019.scalamatsuri.org#836]
現在、日本語中級は「J++」のような略記となっているがわかりにくいというフィードバックが寄せられている。
これを「日本語・中級者向け」というようにわかりやすい表記へ変更したい。

**Comment by grimrose** [comment]
@taisukeoe 
> これを「日本語・中級者向け」というようにわかりやすい表記へ変更したい。

英語の方はどうします？

**Comment by taisukeoe** [comment]
英語だと "English, Intermediate"とかで良い気がしてます
