### ISSUE TITLE
Webロゴ掲載(ワンダーソフト株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#837]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1calqCH0nsYVtl_qXsJMjNoGvwX9zVwZg
リンク先:https://github.com/wonder-soft

**Comment by YumiShibazaki** [comment]
#838 で対応しました。
