### ISSUE TITLE
Web情報掲載(ソルフレア株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#840]
---
title: "ソルフレア株式会社"
logo: ""
plan: 
link: "https://solflare.co.jp/recruit/"
linkTitle: ""
---
### サービス概要

ソルフレア株式会社はエンジニアリングの力で企業のマーケティング支援を行っています。

- RUNWAY 

  ┗ オウンドメディアのプラットフォームサービス。
  オウンドメディア開発・運用、アプリ開発、センサー技術・AIの活用など、企業のマーケティング課題に沿った技術支援、ソリューションの提供を行っています。

- ZIGSOW 

  ┗ あらゆるモノに関するレビューメディア。
  企業の製品やサービスを、一般消費者であるZIGSOWレビュアーが本音でレビューをすることで、世の中に対し真に価値のある有益な情報を提供し、企業へのフィードバックを通して上質なモノづくりを支援しています。

  

### 文化

- 好奇心を持て！

  ┗ 案件ごとに新しい技術にトライすることを推奨。アウトプットの場はたくさんあります。

- コードを紡げ！！

  ┗ コードは過去から現在、そして未来へと繋がっています。今動くコードではなく、なぜそのコードになったかが分かる変更履歴を積み重ねることを大切にしています。

- 怠惰であれ！！！

  ┗ 2度とやりたくないと思った作業は即プログラミング。常に効率化を考え行動します。

### ソルフレアのエンジニア

フロントエンド・サーバーサイド・アプリ・DevOps・R&Dなど、様々なエンジニアが在籍しています。
全員に共通していることは、根っからのプログラミング好きということです。
例えば、 競技プログラマー、Shell芸職人、タイル型ウィンドウマネージャ信者など..。

### Scalaエンジニアを募集中

主に RUNWAY のサーバーサイドの開発をご担当いただける方を募集しています。設計、開発、コードレビューなどの開発工程から、パフォーマンスチューニングや機能改善などサーバーサイド全般をお任せいたします。

【使用技術】Scala(akka-http/slick) / MariaDB / MySQL

Scalaでの開発経験がなくても構いません。
関数型言語が好きな方、興味のある方はぜひお気軽にご応募ください！

**Comment by YumiShibazaki** [comment]
#842 で対応しました。
