### ISSUE TITLE
Webロゴ掲載(ソルフレア株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#841]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/file/d/1jZdk1L3A13MgIT4ekbDDfRg-fIx7jx-p/view?usp=sharing
リンク先:https://solflare.co.jp/

**Comment by YumiShibazaki** [comment]
#842 で対応しました。
