### ISSUE TITLE
Webロゴ掲載(トリプル・ダブリュー・ジャパン株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#843]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/file/d/1DXe9DqVtn73g1SAyVPqdG9Y0nHNFRbad/view?usp=sharing
リンク先:https://www-biz.co/recruit/

**Comment by tomoco95** [comment]
#844 にて対応完了しました。
