### ISSUE TITLE
Webロゴ掲載(株式会社エフ・コード様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#863]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1k5sjPLox39FHq2ZIoz1Bv_GzDSS_eXKd
リンク先:https://www.wantedly.com/projects/148852

**Comment by YumiShibazaki** [comment]
@tomoco95 
ロゴ画像が20:7になっていないみたいです。
サイズ変更をお願いします。

**Comment by tomoco95** [comment]
@YumiShibazaki サイズ調整したのでこれでお願いします！
https://drive.google.com/file/d/1_ZTouYSGATbkF1TN5qwCSODygawQ5HyP/view?usp=sharing

**Comment by YumiShibazaki** [comment]
#864 で対応しました。

**Comment by taisukeoe** [comment]
@YumiShibazaki ありがとう！

ちなみにGitHub豆知識なんだけど、commit messageに `fix #863` という文字を含めると、あら不思議！そのcommitを含んだPullRequest（今回でいう #864 ) がmergeされた時に、 #863のissueもcloseされます。良かったら試してみてね 🙋

**Comment by YumiShibazaki** [comment]
@taisukeoe 
すごい…！！！
Githubほんとお利口！！

**Comment by taisukeoe** [comment]
お利口なのわかる…！
