### ISSUE TITLE
Webロゴ掲載(株式会社オンデオマ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#865]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1MjE21xEkwIKfxsjGiOIVpJLxRIH3ECwO
リンク先:https://www.ondeoma.com/

**Comment by YumiShibazaki** [comment]
#866 で対応しました。
