### ISSUE TITLE
CMのページの作成

### ISSUE THREAD

**Issue by grimrose** [scalajp/2019.scalamatsuri.org#894]
会場で流したCMを公開する

**Comment by Iwaji** [comment]
@grimrose 
ビズリーチさんの内容が変更となる可能性がありますので、いったん作業をストップいただきたくお願いいたします。
さっそくご対応いただいているのに大変申し訳ございません！

**Comment by Iwaji** [comment]
@grimrose すみません・・・
↑上記対応はバックオフィスで作業する内容だとご指摘がありましたので、こちらで対応します。
メンションを飛ばしてお願いしてしまい、失礼いたしました。

**Comment by Iwaji** [comment]
@grimrose cc @taisukeoe
広告用スライドを一部修正しましたので、こちらでご対応いただきたくお願いいたします！
＜修正点＞
・ビズリーチさんを一時的に削除
・上記削除に伴うバランスの修正（大名で４社掲載していたページを３社掲載へ）
https://docs.google.com/presentation/d/13_sVZswY5J3y2o0c0-xSB5MUfAdequXKyvWxpvpwICo/edit#slide=id.g5bdd25bfe7_1_190

**Comment by Iwaji** [comment]
@grimrose cc @taisukeoe 
特に作業いただくことはないのですが、念のため共有させていただきます。
ビズリーチさんの広告用スライド文言の修正版を頂戴したので、リンク先を更新しました！
https://docs.google.com/presentation/d/13_sVZswY5J3y2o0c0-xSB5MUfAdequXKyvWxpvpwICo/edit#slide=id.g5bdd25bfe7_1_190
