### ISSUE TITLE
Webロゴ掲載(株式会社VOYAGE GROUP様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#90]
- [ ] リポジトリにロゴを入れる
- [ ]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1VUxw4uKZn9aaR_PSA_xC1Z5kiALZaX9g
リンク先:https://voyagegroup.com/

**Comment by tomoco95** [comment]
重複してるので #91 を活かします
