### ISSUE TITLE
Webロゴ掲載(株式会社VOYAGE GROUP様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#91]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=15cceWvWsYl_dCC30hI63opS_U_wJB692
リンク先:https://voyagegroup.com/

**Comment by tomoco95** [comment]
#95 で対応中

**Comment by tomoco95** [comment]
done
