### ISSUE TITLE
Webロゴ掲載(ファイブ株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#92]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1udGBu73HueGMUuerFCYgjkKjEDn3zbd3
リンク先:https://www.five-corp.com/

**Comment by tomoco95** [comment]
#96 で対応中

**Comment by tomoco95** [comment]
done
