### ISSUE TITLE
Webロゴ掲載(マーベリック株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2019.scalamatsuri.org#99]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1m0jMLnD-lfhCTFLXgP3vtbreSRYNv3QG
リンク先:https://www.mvrck.co.jp

**Comment by tomoco95** [comment]
ロゴ画像の差し替え依頼です。
出して頂いた画像のサイズが20:7になってなかったので、佐々木さんにサイズ変更を依頼中です。

**Comment by tomoco95** [comment]
done
